[tool.poetry]
name = "burgerbot"
version = "0.1.0"
description = ""
authors = ["sonac <sonag007@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
requests = {extras = ["socks"], version = "^2.26.0"}
beautifulsoup4 = "^4.9.3"
python-telegram-bot = "^13.7"

[tool.poetry.group.dev.dependencies]
black = "^22.8.0"
pre-commit = "^2.20.0"
isort = "^5.10.1"
mypy = "^0.971"
types-requests = "^2.28.11"
types-beautifulsoup4 = "^4.11.6"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"

[tool.mypy]
# todo: re-enable later!
# strict = true
